// <auto-generated />
using ConsoleApp.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Stratos_alpha.Migrations
{
    [DbContext(typeof(FileHashContext))]
    partial class FileHashContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("ConsoleApp.SQLite.DirectoryStatus", b =>
                {
                    b.Property<string>("Path")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Direction");

                    b.Property<long>("Level");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.HasKey("Path");

                    b.ToTable("DirectoryStatusSet");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.GlobalEnvironment", b =>
                {
                    b.Property<string>("key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("value");

                    b.HasKey("key");

                    b.ToTable("GlobalEnvironment");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.UbuntuFile", b =>
                {
                    b.Property<string>("filePath")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fileHash");

                    b.Property<string>("fileName");

                    b.Property<long>("fileSize");

                    b.Property<string>("fileStatus");

                    b.HasKey("filePath");

                    b.ToTable("UbuntuFileSet");
                });
#pragma warning restore 612, 618
        }
    }
}
